package json_files;

import org.json.*;
import org.json.XML;
public class Xml_to_JSON {

	public static void main(String[] args) {
		String xmlString="<library>\r\n"
				+ "<book>\r\n"
				+ "<id>1</id>\r\n"
				+ "<title>Book Title 1</title>\r\n"
				+ "<author>Author 1</author>\r\n"
				+ "<price>102.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>2</id>\r\n"
				+ "<title>Book Title 2</title>\r\n"
				+ "<author>Author 2</author>\r\n"
				+ "<price>105.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>3</id>\r\n"
				+ "<title>Book Title 3</title>\r\n"
				+ "<author>Author 3</author>\r\n"
				+ "<price>107.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>4</id>\r\n"
				+ "<title>Book Title 4</title>\r\n"
				+ "<author>Author 4</author>\r\n"
				+ "<price>110.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>5</id>\r\n"
				+ "<title>Book Title 5</title>\r\n"
				+ "<author>Author 5</author>\r\n"
				+ "<price>112.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>6</id>\r\n"
				+ "<title>Book Title 6</title>\r\n"
				+ "<author>Author 6</author>\r\n"
				+ "<price>115.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>7</id>\r\n"
				+ "<title>Book Title 7</title>\r\n"
				+ "<author>Author 7</author>\r\n"
				+ "<price>117.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>8</id>\r\n"
				+ "<title>Book Title 8</title>\r\n"
				+ "<author>Author 8</author>\r\n"
				+ "<price>120.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>9</id>\r\n"
				+ "<title>Book Title 9</title>\r\n"
				+ "<author>Author 9</author>\r\n"
				+ "<price>122.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>10</id>\r\n"
				+ "<title>Book Title 10</title>\r\n"
				+ "<author>Author 10</author>\r\n"
				+ "<price>125.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>11</id>\r\n"
				+ "<title>Book Title 11</title>\r\n"
				+ "<author>Author 11</author>\r\n"
				+ "<price>127.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>12</id>\r\n"
				+ "<title>Book Title 12</title>\r\n"
				+ "<author>Author 12</author>\r\n"
				+ "<price>130.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>13</id>\r\n"
				+ "<title>Book Title 13</title>\r\n"
				+ "<author>Author 13</author>\r\n"
				+ "<price>132.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>14</id>\r\n"
				+ "<title>Book Title 14</title>\r\n"
				+ "<author>Author 14</author>\r\n"
				+ "<price>135.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>15</id>\r\n"
				+ "<title>Book Title 15</title>\r\n"
				+ "<author>Author 15</author>\r\n"
				+ "<price>137.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>16</id>\r\n"
				+ "<title>Book Title 16</title>\r\n"
				+ "<author>Author 16</author>\r\n"
				+ "<price>140.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>17</id>\r\n"
				+ "<title>Book Title 17</title>\r\n"
				+ "<author>Author 17</author>\r\n"
				+ "<price>142.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>18</id>\r\n"
				+ "<title>Book Title 18</title>\r\n"
				+ "<author>Author 18</author>\r\n"
				+ "<price>145.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>19</id>\r\n"
				+ "<title>Book Title 19</title>\r\n"
				+ "<author>Author 19</author>\r\n"
				+ "<price>147.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>20</id>\r\n"
				+ "<title>Book Title 20</title>\r\n"
				+ "<author>Author 20</author>\r\n"
				+ "<price>150.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>21</id>\r\n"
				+ "<title>Book Title 21</title>\r\n"
				+ "<author>Author 21</author>\r\n"
				+ "<price>152.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>22</id>\r\n"
				+ "<title>Book Title 22</title>\r\n"
				+ "<author>Author 22</author>\r\n"
				+ "<price>155.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>23</id>\r\n"
				+ "<title>Book Title 23</title>\r\n"
				+ "<author>Author 23</author>\r\n"
				+ "<price>157.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>24</id>\r\n"
				+ "<title>Book Title 24</title>\r\n"
				+ "<author>Author 24</author>\r\n"
				+ "<price>160.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>25</id>\r\n"
				+ "<title>Book Title 25</title>\r\n"
				+ "<author>Author 25</author>\r\n"
				+ "<price>162.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>26</id>\r\n"
				+ "<title>Book Title 26</title>\r\n"
				+ "<author>Author 26</author>\r\n"
				+ "<price>165.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>27</id>\r\n"
				+ "<title>Book Title 27</title>\r\n"
				+ "<author>Author 27</author>\r\n"
				+ "<price>167.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>28</id>\r\n"
				+ "<title>Book Title 28</title>\r\n"
				+ "<author>Author 28</author>\r\n"
				+ "<price>170.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>29</id>\r\n"
				+ "<title>Book Title 29</title>\r\n"
				+ "<author>Author 29</author>\r\n"
				+ "<price>172.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>30</id>\r\n"
				+ "<title>Book Title 30</title>\r\n"
				+ "<author>Author 30</author>\r\n"
				+ "<price>175.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>31</id>\r\n"
				+ "<title>Book Title 31</title>\r\n"
				+ "<author>Author 31</author>\r\n"
				+ "<price>177.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>32</id>\r\n"
				+ "<title>Book Title 32</title>\r\n"
				+ "<author>Author 32</author>\r\n"
				+ "<price>180.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>33</id>\r\n"
				+ "<title>Book Title 33</title>\r\n"
				+ "<author>Author 33</author>\r\n"
				+ "<price>182.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>34</id>\r\n"
				+ "<title>Book Title 34</title>\r\n"
				+ "<author>Author 34</author>\r\n"
				+ "<price>185.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>35</id>\r\n"
				+ "<title>Book Title 35</title>\r\n"
				+ "<author>Author 35</author>\r\n"
				+ "<price>187.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>36</id>\r\n"
				+ "<title>Book Title 36</title>\r\n"
				+ "<author>Author 36</author>\r\n"
				+ "<price>190.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>37</id>\r\n"
				+ "<title>Book Title 37</title>\r\n"
				+ "<author>Author 37</author>\r\n"
				+ "<price>192.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>38</id>\r\n"
				+ "<title>Book Title 38</title>\r\n"
				+ "<author>Author 38</author>\r\n"
				+ "<price>195.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>39</id>\r\n"
				+ "<title>Book Title 39</title>\r\n"
				+ "<author>Author 39</author>\r\n"
				+ "<price>197.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>40</id>\r\n"
				+ "<title>Book Title 40</title>\r\n"
				+ "<author>Author 40</author>\r\n"
				+ "<price>200.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>41</id>\r\n"
				+ "<title>Book Title 41</title>\r\n"
				+ "<author>Author 41</author>\r\n"
				+ "<price>202.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>42</id>\r\n"
				+ "<title>Book Title 42</title>\r\n"
				+ "<author>Author 42</author>\r\n"
				+ "<price>205.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>43</id>\r\n"
				+ "<title>Book Title 43</title>\r\n"
				+ "<author>Author 43</author>\r\n"
				+ "<price>207.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>44</id>\r\n"
				+ "<title>Book Title 44</title>\r\n"
				+ "<author>Author 44</author>\r\n"
				+ "<price>210.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>45</id>\r\n"
				+ "<title>Book Title 45</title>\r\n"
				+ "<author>Author 45</author>\r\n"
				+ "<price>212.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>46</id>\r\n"
				+ "<title>Book Title 46</title>\r\n"
				+ "<author>Author 46</author>\r\n"
				+ "<price>215.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>47</id>\r\n"
				+ "<title>Book Title 47</title>\r\n"
				+ "<author>Author 47</author>\r\n"
				+ "<price>217.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>48</id>\r\n"
				+ "<title>Book Title 48</title>\r\n"
				+ "<author>Author 48</author>\r\n"
				+ "<price>220.0</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>49</id>\r\n"
				+ "<title>Book Title 49</title>\r\n"
				+ "<author>Author 49</author>\r\n"
				+ "<price>222.5</price>\r\n"
				+ "</book>\r\n"
				+ "<book>\r\n"
				+ "<id>50</id>\r\n"
		 		+ "<title>Book Title 50</title>\r\n"
				+ "<author>Author 50</author>\r\n"
				+ "<price>225.0</price>\r\n"
				+ "</book>\r\n"
				+ "</library>";
		
		JSONObject obj=XML.toJSONObject(xmlString);
		
		String jsonString=obj.toString();
		System.out.println(jsonString);

	}

}
